### ISSUE TITLE
Variable update crash when posting to slack

### ISSUE THREAD

**Issue by rossille** [transcovo/letsdeploy#26]
(letsdeploy) rossille_prod@rossille-HP-EliteBook-850-G3:~/letsdeploy$ ./config_deploy_changes.py prod
    ADD PAYMENT_ENABLE_CASH_PAYMENT: x ---> "false" ? (y/n): y
Traceback (most recent call last):
  File "./config_deploy_changes.py", line 5, in <module>
    run()
  File "/home/rossille_prod/letsdeploy/src/scripts/config_deploy_changes.py", line 134, in run
    apply_pending_changes(env, current_app, pending_changes, gateway)
  File "/home/rossille_prod/letsdeploy/src/scripts/config_deploy_changes.py", line 84, in apply_pending_changes
    post_config_change(env, app_name, pending_changes)
  File "/home/rossille_prod/letsdeploy/src/scripts/config_deploy_changes.py", line 76, in post_config_change
    slack.post(env.slack_integration, 'CONFIG UPDATE / %s' % app_name, ':gear:', message, {'app_name': app_name})
TypeError: post() takes 4 positional arguments but 5 were given

**Comment by rossille** [comment]
Duplicate: #27
